### ISSUE TITLE
No module named 'ansible.plugins.action.network'

### ISSUE THREAD

**Issue by pavelion** [ansible-collections/mellanox.onyx#10]
##### SUMMARY

mellanox.onyx.plugins.action.onyx_config imports ansible.plugins.action.network which is no longer available in Ansible 2.10 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mellanox.onyx.plugins.action.onyx_config

##### ANSIBLE VERSION

```paste below
ansible 2.10.1
  python version = 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) [Clang 6.0 (clang-600.0.57)]
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: mellanox_onyx
  gather_facts: false
  tasks:
    - mellanox.onyx.onyx_config:
        lines:
          - configuration write
```

##### ACTUAL RESULTS

```paste below
PLAY [mellanox_onyx] *****************************************************************************************************************************************************************************************************************************************
ERROR! Unexpected Exception, this is probably a bug: No module named 'ansible.plugins.action.network'
```
