### ISSUE TITLE
onyx_vlan is missing example of aggregate

### ISSUE THREAD

**Issue by thizmo** [ansible-collections/mellanox.onyx#22]
##### SUMMARY
I do not get the aggregate working in onyx_vlan.
There is no example in the documenation at all.

While this works:
```
    - name: Remove some vlan
      onyx_vlan:
        vlan_id: "11"
        name: my-vlan-11
        state: absent
      tags: vlan-config
```
While this does not work.
I can't find any example on how this is supposed to work.

``` 
    - name: Remove some vlans
      onyx_vlan:
         aggregate:
            - { vlan_id: 11, name: my-vlan-11 }
            - { vlan_id: 49, name: my-vlan-49 }
        state: absent
      tags: vlan-config
```

Another small hint:
Using the playbook for vlan_id: 11 without the " " it tried to remove vlan 1...
So luckily this is not supported... 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
onyx_vlan

##### ANSIBLE VERSION

```paste below
ansible 2.9.27
  config file = .ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Mar  1 2021, 11:38:31) [GCC 5.4.0 20160609]
```
