### ISSUE TITLE
minor bug in mellanox.onyx.onyx_lldp module documentation example

### ISSUE THREAD

**Issue by janfrode** [ansible-collections/mellanox.onyx#30]
The examples at https://docs.ansible.com/ansible/latest/collections/mellanox/onyx/onyx_lldp_module.html says:

```
- name: Enable LLDP protocol
  onyx_lldp:
    state: present

- name: Disable LLDP protocol
  onyx_lldp:
    state: lldp
```

That last "state: lldp" should be "state: absent" according to above documentation, and also testing.
